### ISSUE TITLE
Crash when using Closest Match error handler

### ISSUE THREAD

**Issue by mmmds** [cherokee/webserver#1270]
If the server is configured to use the Closest Match error handler and the server receives an invalid HTTP request it crashes because of a not initialized request buffer.

Steps to reproduce:
1. Use the default configuration and set the Closest Match error handler.
```
config!version = 001002104
server!bind!1!port = 80
server!keepalive = 1
server!keepalive_max_requests = 500
server!panic_action = /home/osboxes/fuzz-cherokee/webserver-clean/usr/bin/cherokee-panic
server!pid_file = /home/osboxes/fuzz-cherokee/webserver-clean/var/run/cherokee.pid
server!server_tokens = full
server!timeout = 15
vserver!1!directory_index = index.html
vserver!1!document_root = /home/osboxes/fuzz-cherokee/webserver-clean/var/www
vserver!1!error_handler = error_nn
vserver!1!error_writer!filename = /home/osboxes/fuzz-cherokee/webserver-clean/var/log/cherokee.error
vserver!1!error_writer!type = file
vserver!1!logger = combined
vserver!1!logger!access!buffsize = 16384
vserver!1!logger!access!filename = /home/osboxes/fuzz-cherokee/webserver-clean/var/log/cherokee.access
vserver!1!logger!access!type = file
vserver!1!nick = default
[...]
```
2. Run the server
```
$ sudo ./usr/sbin/cherokee-worker -C ../x.conf
```
3. Send an invalid request
```
$ echo -e "GET / 1 HTTP/1.1\r\n\r\nHost: 127.0.0.1\r\n\r\n" | nc 127.0.0.1 80
```
4. Observe the crash
```
Cherokee Web Server 1.2.104 (Oct 11 2021): Listening on port ALL:80, TLS
disabled, IPv6 enabled, using epoll, 4096 fds system limit, max. 2041
connections, 5 threads, 408 connections per thread, standard scheduling policy
Cherokee feels panic!
The Cherokee 'panic action' script, /home/osboxes/fuzz-cherokee/webserver-clean/usr/bin/cherokee-panic,
was called for pid 19654 (/home/osboxes/fuzz-cherokee/webserver-clean/usr/sbin/cherokee-worker).

Below is a backtrace for this process generated with gdb, which shows
the state of the program at the time the error occured.  You are
encouraged to submit this information as a bug report in the Cherokee
bug tracking system:  http://bugs.cherokee-project.com

Operating System: Linux osboxes 5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Debugger: /usr/bin/gdb

[New LWP 19655]
[New LWP 19656]
[New LWP 19657]
[New LWP 19658]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f8a973acdff in __GI___wait4 (pid=19663, stat_loc=stat_loc@entry=0x7ffe1fb6aaa8, options=options@entry=0, usage=usage@entry=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
27	../sysdeps/unix/sysv/linux/wait4.c: No such file or directory.
$1 = 0x7f8a97537c60 "1.2.104"

Thread 5 (Thread 0x7f8a95a0a700 (LWP 19658)):
#0  __lll_lock_wait (futex=futex@entry=0x5606034787a0, private=0) at lowlevellock.c:52
        __ret = <optimized out>
#1  0x00007f8a975590a3 in __GI___pthread_mutex_lock (mutex=0x5606034787a0) at ../nptl/pthread_mutex_lock.c:80
        __futex = 0x5606034787a0
        type = <optimized out>
        __PRETTY_FUNCTION__ = "__pthread_mutex_lock"
        id = <optimized out>
#2  0x00007f8a974dc142 in watch_accept_MULTI_THREAD (thd=0x560603488450, block=true, fdwatch_msecs=1000) at thread.c:1912
        ret = ret_ok
        unlocked = 1000
        bind = 0x5606034885d0
        i = 0x5606034885d0
        yield = false
        srv = 0x560603478600
        __func__ = "watch_accept_MULTI_THREAD"
#3  0x00007f8a974dc562 in cherokee_thread_step_MULTI_THREAD (thd=0x560603488450, dont_block=false) at thread.c:2067
        ret = ret_ok
        time_updated = true
        can_block = true
        srv = 0x560603478600
        fdwatch_msecs = 1000
#4  0x00007f8a974d8d5c in thread_routine (data=0x560603488450) at thread.c:99
        thread = 0x560603488450
#5  0x00007f8a97556609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140233192548096, 6185705875487073394, 140729430486830, 140729430486831, 140729430487024, 140233192546240, -6139213362372533134, -6139211054186093454}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007f8a973e9293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 4 (Thread 0x7f8a9620b700 (LWP 19657)):
#0  __lll_lock_wait (futex=futex@entry=0x5606034787a0, private=0) at lowlevellock.c:52
        __ret = <optimized out>
#1  0x00007f8a975590a3 in __GI___pthread_mutex_lock (mutex=0x5606034787a0) at ../nptl/pthread_mutex_lock.c:80
        __futex = 0x5606034787a0
        type = <optimized out>
        __PRETTY_FUNCTION__ = "__pthread_mutex_lock"
        id = <optimized out>
#2  0x00007f8a974dc142 in watch_accept_MULTI_THREAD (thd=0x560603485dd0, block=true, fdwatch_msecs=1000) at thread.c:1912
        ret = ret_ok
        unlocked = 1000
        bind = 0x560603485f50
        i = 0x560603485f50
        yield = false
        srv = 0x560603478600
        __func__ = "watch_accept_MULTI_THREAD"
#3  0x00007f8a974dc562 in cherokee_thread_step_MULTI_THREAD (thd=0x560603485dd0, dont_block=false) at thread.c:2067
        ret = ret_ok
        time_updated = true
        can_block = true
        srv = 0x560603478600
        fdwatch_msecs = 1000
#4  0x00007f8a974d8d5c in thread_routine (data=0x560603485dd0) at thread.c:99
        thread = 0x560603485dd0
#5  0x00007f8a97556609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140233200940800, 6185705875487073394, 140729430486830, 140729430486831, 140729430487024, 140233200938944, -6139207865351265166, -6139211054186093454}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007f8a973e9293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 3 (Thread 0x7f8a96a0c700 (LWP 19656)):
#0  0x00007f8a973e95ce in epoll_wait (epfd=8, events=0x5606034bfc20, maxevents=816, timeout=1000) at ../sysdeps/unix/sysv/linux/epoll_wait.c:30
        resultvar = 18446744073709551612
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f8a9750eb7f in _watch (fdp=0x5606034872d0, timeout_msecs=1000) at fdpoll-epoll.c:243
        i = 0
#2  0x00007f8a97521a69 in cherokee_fdpoll_watch (fdp=0x5606034872d0, timeout_msecs=1000) at fdpoll.c:338
No locals.
#3  0x00007f8a974dc227 in watch_accept_MULTI_THREAD (thd=0x560603487110, block=true, fdwatch_msecs=1000) at thread.c:1944
        ret = ret_ok
        unlocked = 1000
        bind = 0x560603487290
        i = 0x560603478790
        yield = false
        srv = 0x560603478600
        __func__ = "watch_accept_MULTI_THREAD"
#4  0x00007f8a974dc562 in cherokee_thread_step_MULTI_THREAD (thd=0x560603487110, dont_block=false) at thread.c:2067
        ret = ret_ok
        time_updated = true
        can_block = true
        srv = 0x560603478600
        fdwatch_msecs = 1000
#5  0x00007f8a974d8d5c in thread_routine (data=0x560603487110) at thread.c:99
        thread = 0x560603487110
#6  0x00007f8a97556609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140233209333504, 6185705875487073394, 140729430486830, 140729430486831, 140729430487024, 140233209331648, -6139206766376508302, -6139211054186093454}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#7  0x00007f8a973e9293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 2 (Thread 0x7f8a9720d700 (LWP 19655)):
#0  __lll_lock_wait (futex=futex@entry=0x5606034787a0, private=0) at lowlevellock.c:52
        __ret = <optimized out>
#1  0x00007f8a975590a3 in __GI___pthread_mutex_lock (mutex=0x5606034787a0) at ../nptl/pthread_mutex_lock.c:80
        __futex = 0x5606034787a0
        type = <optimized out>
        __PRETTY_FUNCTION__ = "__pthread_mutex_lock"
        id = <optimized out>
#2  0x00007f8a974dc142 in watch_accept_MULTI_THREAD (thd=0x560603479300, block=true, fdwatch_msecs=1000) at thread.c:1912
        ret = ret_ok
        unlocked = 1000
        bind = 0x560603479480
        i = 0x560603479480
        yield = false
        srv = 0x560603478600
        __func__ = "watch_accept_MULTI_THREAD"
#3  0x00007f8a974dc562 in cherokee_thread_step_MULTI_THREAD (thd=0x560603479300, dont_block=false) at thread.c:2067
        ret = ret_ok
        time_updated = true
        can_block = true
        srv = 0x560603478600
        fdwatch_msecs = 1000
#4  0x00007f8a974d8d5c in thread_routine (data=0x560603479300) at thread.c:99
        thread = 0x560603479300
#5  0x00007f8a97556609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140233217726208, 6185705875487073394, 140729430486830, 140729430486831, 140729430487024, 140233217724352, -6139210061153295246, -6139211054186093454}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007f8a973e9293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 1 (Thread 0x7f8a9724d6c0 (LWP 19654)):
#0  0x00007f8a973acdff in __GI___wait4 (pid=19663, stat_loc=stat_loc@entry=0x7ffe1fb6aaa8, options=options@entry=0, usage=usage@entry=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
        resultvar = 18446744073709551104
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f8a973acd7b in __GI___waitpid (pid=<optimized out>, stat_loc=stat_loc@entry=0x7ffe1fb6aaa8, options=options@entry=0) at waitpid.c:38
No locals.
#2  0x00007f8a9731c0e7 in do_system (line=<optimized out>) at ../sysdeps/posix/system.c:172
        __result = <optimized out>
        _buffer = {__routine = 0x7f8a9731c290 <cancel_handler>, __arg = 0x7ffe1fb6aab0, __canceltype = 0, __prev = 0x0}
        _avail = 1
        cancel_args = {quit = 0x7f8a974b5200 <quit>, intr = 0x7f8a974b52a0 <intr>, pid = 19663}
        status = -1
        ret = 0
        pid = 19663
        sa = {__sigaction_handler = {sa_handler = 0x1, sa_sigaction = 0x1}, sa_mask = {__val = {65536, 0 <repeats 15 times>}}, sa_flags = 0, sa_restorer = 0x560602e504c0 <_start>}
        omask = {__val = {1024, 0, 75, 140729430485856, 140233220730737, 140729430486288, 94583824866672, 140233219072282, 140233220314786, 140729430486096, 2676586395008836901, 2676586395008836901, 0, 0, 0, 0}}
        reset = {__val = {6, 0 <repeats 15 times>}}
        spawn_attr = {__flags = 12, __pgrp = 0, __sd = {__val = {6, 0 <repeats 15 times>}}, __ss = {__val = {1024, 0, 75, 140729430485856, 140233220730737, 140729430486288, 94583824866672, 140233219072282, 140233220314786, 140729430486096, 2676586395008836901, 2676586395008836901, 0, 0, 0, 0}}, __sp = {sched_priority = 0}, __policy = 0, __pad = {0 <repeats 16 times>}}
        __cnt = <optimized out>
        __set = <optimized out>
        __cnt = <optimized out>
        __set = <optimized out>
#3  0x00007f8a974d47d4 in cherokee_server_handle_panic (srv=0x560603478600) at server.c:1909
        re = 532066112
        cmd = {buf = 0x560603485d70 "/home/osboxes/fuzz-cherokee/webserver-clean/usr/bin/cherokee-panic 19654", size = 76, len = 72}
#4  0x0000560602e50731 in signals_handler (sig=11, si=0x7ffe1fb6aff0, context=0x7ffe1fb6aec0) at main_worker.c:154
No locals.
#5  <signal handler called>
No locals.
#6  __strrchr_avx2 () at ../sysdeps/x86_64/multiarch/strrchr-avx2.S:54
No locals.
#7  0x00007f8a9758397b in get_nearest_name (conn=0x5606034875e0, local_dir=0x560603487a18, request=0x560603487a38, output=0x560603487e78) at handler_error_nn.c:118
        ret = ret_ok
        rest = 0x560603487e78 ""
        thread = 0x5606034bd0c0
        req = 0x5606034bd1c0
#8  0x00007f8a97583a94 in error_nn_init (hdl=0x5606034860a0) at handler_error_nn.c:150
        ret = ret_ok
        conn = 0x5606034875e0
#9  0x00007f8a974ceb70 in cherokee_handler_init (hdl=0x5606034860a0) at handler.c:93
        init_func = 0x7f8a97583a39 <error_nn_init>
#10 0x00007f8a974ce166 in cherokee_connection_open_request (conn=0x5606034875e0) at connection.c:2683
No locals.
#11 0x00007f8a974da909 in process_active_connections (thd=0x5606034bd0c0) at thread.c:1165
        re = 4
        ret = 1000
        len = 94583825092800
        i = 0x5606034875e0
        tmp = 0x5606034bd200
        conn = 0x5606034875e0
        srv = 0x560603478600
        blocking = -1756511310
        __func__ = "process_active_connections"
#12 0x00007f8a974dc5a2 in cherokee_thread_step_MULTI_THREAD (thd=0x5606034bd0c0, dont_block=true) at thread.c:2086
        ret = ret_ok
        time_updated = true
        can_block = false
        srv = 0x560603478600
        fdwatch_msecs = 1000
#13 0x00007f8a974d2798 in cherokee_server_step (srv=0x560603478600) at server.c:1157
        ret = ret_ok
#14 0x0000560602e50f4d in main (argc=3, argv=0x7ffe1fb6b748) at main_worker.c:407
        ret = ret_eagain
A debugging session is active.

	Inferior 1 [process 19654] will be detached.

Quit anyway? (y or n) [answered Y; input not from terminal]
[Inferior 1 (process 19654) detached]
Aborted
```

Below is the crash situation analyzed under the debugger. `request->buf` is not initialized, thus segmentation fault occurs when passed to `strrchr`.
```
$ sudo gdb --args ./usr/sbin/cherokee-worker -C ../x.conf
[...]
(gdb) b handler_error_nn.c:118
[...]
(gdb) r
Starting program: /home/osboxes/fuzz-cherokee/webserver-clean/usr/sbin/cherokee-worker -C ../x.conf
[...]
Cherokee Web Server 1.2.104 (Oct 11 2021): Listening on port ALL:80, TLS
disabled, IPv6 enabled, using epoll, 4096 fds system limit, max. 2041
connections, 5 threads, 408 connections per thread, standard scheduling policy

Thread 1 "cherokee-worker" hit Breakpoint 1, get_nearest_name (conn=0x55555556b5e0, local_dir=0x55555556ba18, 
    request=0x55555556ba38, output=0x55555556be78) at handler_error_nn.c:118
118     rest = strrchr (request->buf, '/');
(gdb) print *request
$1 = {buf = 0x0, size = 0, len = 0}
(gdb) c
Continuing.

Thread 1 "cherokee-worker" received signal SIGSEGV, Segmentation fault.
__strrchr_avx2 () at ../sysdeps/x86_64/multiarch/strrchr-avx2.S:54
54  ../sysdeps/x86_64/multiarch/strrchr-avx2.S: No such file or directory.
```

When the server receives a correct request, the buffer is initialized and the request is processed correctly.

**Comment by skinkie** [comment]
Thanks for this advanced report. Are you using the latest github version or a release from somewhere?
